### ISSUE TITLE
Missing commit() Connection method

### ISSUE THREAD

**Issue by prochac** [firebolt-db/firebolt-python-sdk#74]
```
.commit()
...

Database modules that do not support transactions should implement this method with void functionality.
~ PEP-249 (https://www.python.org/dev/peps/pep-0249/#commit)
```
I know it's just should, but it would be nice to add it and mention the lack of transactions in Firebolt engine.

**Comment by stepansergeevitch** [comment]
Hey @prochac, thanks for your issue. I agree, it makes sense to add this method even if we don't have transactions in Firebolt. I will add it.
